# Generated by Django 5.1.4 on 2025-01-07 11:05

import django.db.models.deletion
import linkshortener.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkshortener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mylink',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mylink',
            name='hash',
            field=models.CharField(default=linkshortener.utils.generate_unique_hash, max_length=50, unique=True),
        ),
    ]
